 <center> 
  <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">About</h2>
            <h3 class="section-subheading text-muted">ประวัติผู้พัฒนาเว็บไซต์</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <ul class="timeline">
            
                <div class="timeline-image">
                  <img class=" img-fluid" src="img/about/1.jpg" width="200" alt="">
                </div>
            <br>
               
                    <h4>นาย ปฐกร  รักเชื้อ</h4>
                    <h4 class="subheading">รหัสนักศึกษา 590610638</h4>
           
            
        
             
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="img/about/2.png" alt="">
                </div>
                <div class="timeline-panel">
            
                  <div class="timeline-heading">
                    <h4>กำลังศีกษาอยู่ที่</h4>
                    <h4 class="subheading">มหาวิทยาลัยเชียงใหม่</h4>
                  </div>
                </div>
            <br>
              
                 
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h4>คณะวิศวกรรมศาสตร์</h4>
                    <h4 class="subheading">สาขา วิศวกรรมศาสตร์คอมพิวเตอร์</h4>
                  </div>
                </div>

 </ul>
</div>
</div>
</div>
   </center>